table dim_instrument
	lineageTag: 0dd15666-3858-5d2d-8efa-852c6a1b0f22

	column 'instrument_id'
		dataType: string
		lineageTag: c4f186b7-6cf4-5914-90fd-badb94cb0cf3
		summarizeBy: none
		sourceColumn: instrument_id

		annotation SummarizationSetBy = User

	column 'name'
		dataType: string
		lineageTag: 713ab7d4-663d-5169-a279-9d79772d116f
		summarizeBy: none
		sourceColumn: name

		annotation SummarizationSetBy = User

	column 'asset_class'
		dataType: string
		lineageTag: 61b9d4ca-45fa-5417-88b0-efcaef64ded6
		summarizeBy: none
		sourceColumn: asset_class

		annotation SummarizationSetBy = User

	column 'desk'
		dataType: string
		lineageTag: a15186dd-f8da-5c69-b634-3276bf3a3baf
		summarizeBy: none
		sourceColumn: desk

		annotation SummarizationSetBy = User

	column 'currency'
		dataType: string
		lineageTag: d8cb74f7-707e-58b2-bd70-615e3a3079b0
		summarizeBy: none
		sourceColumn: currency

		annotation SummarizationSetBy = User

	column 'quote'
		dataType: string
		lineageTag: a92bf2d9-d636-5ba2-b822-0afb91ba7f64
		summarizeBy: none
		sourceColumn: quote

		annotation SummarizationSetBy = User

	column 'source'
		dataType: string
		lineageTag: 8fddf6f3-21f4-53ad-b252-53675af2ea91
		summarizeBy: none
		sourceColumn: source

		annotation SummarizationSetBy = User

	column 'ticker'
		dataType: string
		lineageTag: 6b8bd6c1-b89f-591c-93dc-c07770e4dd77
		summarizeBy: none
		sourceColumn: ticker

		annotation SummarizationSetBy = User

	column 'tenor_years'
		dataType: double
		lineageTag: 65586e96-45b6-5586-b072-a05adb6603d3
		summarizeBy: none
		sourceColumn: tenor_years

		annotation SummarizationSetBy = User

	partition dim_instrument = m
		mode: import
		source =
				let
				    Source = Csv.Document(File.Contents(BiFolder & "dim_instrument.csv"), [Delimiter = ",", Encoding = 65001, QuoteStyle = QuoteStyle.Csv]),
				    Promoted = Table.PromoteHeaders(Source, [PromoteAllScalars = true]),
				    Blanks = Table.ReplaceValue(Promoted, "", null, Replacer.ReplaceValue, Table.ColumnNames(Promoted)),
				    Typed = Table.TransformColumnTypes(Blanks, {{"instrument_id", type text}, {"name", type text}, {"asset_class", type text}, {"desk", type text}, {"currency", type text}, {"quote", type text}, {"source", type text}, {"ticker", type text}, {"tenor_years", type number}}, "en-US")
				in
				    Typed

	annotation PBI_ResultType = Table
