table fact_gs_var
	lineageTag: e1546e53-4a12-527a-9c2b-465fa2a3cf6b

	measure 'Total VaR (USD m)' = CALCULATE ( SUM ( fact_gs_var[total] ), fact_gs_var[measure] = "average", fact_gs_var[horizon] = "quarter" )
		formatString: 0
		lineageTag: d7407c00-d809-5379-a937-d2375ac67cea

	measure 'Interest rates (USD m)' = CALCULATE ( SUM ( fact_gs_var[interest_rates] ), fact_gs_var[measure] = "average", fact_gs_var[horizon] = "quarter" )
		formatString: 0
		lineageTag: 93627124-4b22-55a7-94e5-496f6cf9ba36

	measure 'Equity prices (USD m)' = CALCULATE ( SUM ( fact_gs_var[equity_prices] ), fact_gs_var[measure] = "average", fact_gs_var[horizon] = "quarter" )
		formatString: 0
		lineageTag: 47fab326-3983-58c2-805b-f626fe3c6575

	measure 'Currency rates (USD m)' = CALCULATE ( SUM ( fact_gs_var[currency_rates] ), fact_gs_var[measure] = "average", fact_gs_var[horizon] = "quarter" )
		formatString: 0
		lineageTag: 6c951e51-99ce-5324-a6f8-4439c26a36bb

	measure 'Commodity prices (USD m)' = CALCULATE ( SUM ( fact_gs_var[commodity_prices] ), fact_gs_var[measure] = "average", fact_gs_var[horizon] = "quarter" )
		formatString: 0
		lineageTag: ffc295d8-47e3-51c8-a746-fffeed917a9b

	measure 'Latest quarter, total (USD m)' = VAR d = CALCULATE ( MAX ( fact_gs_var[period_end] ), fact_gs_var[measure] = "average", fact_gs_var[horizon] = "quarter" ) RETURN CALCULATE ( SUM ( fact_gs_var[total] ), fact_gs_var[measure] = "average", fact_gs_var[horizon] = "quarter", fact_gs_var[period_end] = d )
		formatString: 0
		lineageTag: 7d6c820e-56f3-5f87-970a-dbe01f9b8a0e

	measure 'Quarters published' = CALCULATE ( COUNTROWS ( fact_gs_var ), fact_gs_var[measure] = "average", fact_gs_var[horizon] = "quarter" )
		formatString: 0
		lineageTag: 02ac752c-afcb-50c3-b10a-9b543c00c24e

	column 'accession'
		dataType: string
		lineageTag: 8c886e8b-4c7b-5762-9e2a-708e19cd285e
		summarizeBy: none
		sourceColumn: accession

		annotation SummarizationSetBy = User

	column 'form'
		dataType: string
		lineageTag: cf22beb2-523c-5c26-a4dc-d2f557b1fd6e
		summarizeBy: none
		sourceColumn: form

		annotation SummarizationSetBy = User

	column 'filed'
		dataType: dateTime
		formatString: d mmm yyyy
		lineageTag: 1ff8e01a-4c5a-5165-afc9-0768df1c6d21
		summarizeBy: none
		sourceColumn: filed

		annotation SummarizationSetBy = User

	column 'period_end'
		dataType: dateTime
		formatString: d mmm yyyy
		lineageTag: aa0ea001-fa2a-5e49-95a3-1ada5d6e7103
		summarizeBy: none
		sourceColumn: period_end

		annotation SummarizationSetBy = User

	column 'measure'
		dataType: string
		lineageTag: b6141be0-08ff-58b6-ad31-7b26ad7477ac
		summarizeBy: none
		sourceColumn: measure

		annotation SummarizationSetBy = User

	column 'horizon'
		dataType: string
		lineageTag: f867e036-8672-5c8d-a177-a7eedb2bdfe9
		summarizeBy: none
		sourceColumn: horizon

		annotation SummarizationSetBy = User

	column 'column'
		dataType: int64
		lineageTag: 3d78a9eb-70f3-5763-a95c-9350b5c6f13c
		summarizeBy: none
		sourceColumn: column

		annotation SummarizationSetBy = User

	column 'interest_rates'
		dataType: double
		lineageTag: 5f5daaf8-0dac-54be-a85c-4ceb4d671c96
		summarizeBy: none
		sourceColumn: interest_rates

		annotation SummarizationSetBy = User

	column 'equity_prices'
		dataType: double
		lineageTag: 5343329c-34f4-5b2f-8b50-ae327a2f7b04
		summarizeBy: none
		sourceColumn: equity_prices

		annotation SummarizationSetBy = User

	column 'currency_rates'
		dataType: double
		lineageTag: 77f36618-0391-511e-bebf-f74f80e4b547
		summarizeBy: none
		sourceColumn: currency_rates

		annotation SummarizationSetBy = User

	column 'commodity_prices'
		dataType: double
		lineageTag: 9a561102-9e7e-53b0-b9b8-abcba27bef28
		summarizeBy: none
		sourceColumn: commodity_prices

		annotation SummarizationSetBy = User

	column 'diversification'
		dataType: double
		lineageTag: bbcd25d5-9cf9-50fa-bd61-497a95ea216a
		summarizeBy: none
		sourceColumn: diversification

		annotation SummarizationSetBy = User

	column 'total'
		dataType: double
		lineageTag: 99413035-7be5-592f-b1ca-a8d013923d12
		summarizeBy: none
		sourceColumn: total

		annotation SummarizationSetBy = User

	column 'identity_gap'
		dataType: double
		lineageTag: 4074bd24-0b91-5838-8a21-1349bde13155
		summarizeBy: none
		sourceColumn: identity_gap

		annotation SummarizationSetBy = User

	partition fact_gs_var = m
		mode: import
		source =
				let
				    Source = Csv.Document(File.Contents(BiFolder & "fact_gs_var.csv"), [Delimiter = ",", Encoding = 65001, QuoteStyle = QuoteStyle.Csv]),
				    Promoted = Table.PromoteHeaders(Source, [PromoteAllScalars = true]),
				    Blanks = Table.ReplaceValue(Promoted, "", null, Replacer.ReplaceValue, Table.ColumnNames(Promoted)),
				    Typed = Table.TransformColumnTypes(Blanks, {{"accession", type text}, {"form", type text}, {"filed", type date}, {"period_end", type date}, {"measure", type text}, {"horizon", type text}, {"column", Int64.Type}, {"interest_rates", type number}, {"equity_prices", type number}, {"currency_rates", type number}, {"commodity_prices", type number}, {"diversification", type number}, {"total", type number}, {"identity_gap", type number}}, "en-US")
				in
				    Typed

	annotation PBI_ResultType = Table
