table fact_stress
	lineageTag: e29a483c-36d2-5ac7-9bbb-f679230a334a

	column 'date'
		dataType: dateTime
		formatString: d mmm yyyy
		lineageTag: 0dfbbf7d-e0f1-5bc9-afe2-aa8fb0e1f9d9
		summarizeBy: none
		sourceColumn: date

		annotation SummarizationSetBy = User

	column 'scenario'
		dataType: string
		lineageTag: 595ed885-94c3-5842-a021-bd7abd0f8d0b
		summarizeBy: none
		sourceColumn: scenario

		annotation SummarizationSetBy = User

	column 'kind'
		dataType: string
		lineageTag: 4b876e34-48cf-5405-9f63-b49e9da8d9a7
		summarizeBy: none
		sourceColumn: kind

		annotation SummarizationSetBy = User

	column 'desk'
		dataType: string
		lineageTag: bf242712-23c1-5270-b044-7a03594806e5
		summarizeBy: none
		sourceColumn: desk

		annotation SummarizationSetBy = User

	column 'pnl_gbp'
		dataType: double
		lineageTag: 6fe7a459-e4e5-5bd5-b986-3bbb5c685be2
		summarizeBy: none
		sourceColumn: pnl_gbp

		annotation SummarizationSetBy = User

	column 'scenario_name'
		dataType: string
		lineageTag: 58dbc7d5-69dc-593d-a1ff-4e24b9955218
		summarizeBy: none
		sourceColumn: scenario_name

		annotation SummarizationSetBy = User

	partition fact_stress = m
		mode: import
		source =
				let
				    Source = Csv.Document(File.Contents(BiFolder & "fact_stress.csv"), [Delimiter = ",", Encoding = 65001, QuoteStyle = QuoteStyle.Csv]),
				    Promoted = Table.PromoteHeaders(Source, [PromoteAllScalars = true]),
				    Blanks = Table.ReplaceValue(Promoted, "", null, Replacer.ReplaceValue, Table.ColumnNames(Promoted)),
				    Typed = Table.TransformColumnTypes(Blanks, {{"date", type date}, {"scenario", type text}, {"kind", type text}, {"desk", type text}, {"pnl_gbp", type number}, {"scenario_name", type text}}, "en-US")
				in
				    Typed

	annotation PBI_ResultType = Table
