table fact_risk
	lineageTag: 5ddbaa05-8f0b-55d8-89b0-3e7e8b863b26

	measure '99% VaR (GBP m)' = CALCULATE ( SUM ( fact_risk[value_gbp] ), fact_risk[method] = "hs_equal", fact_risk[measure] = "VaR99", fact_risk[scope] = "total" ) / 1e6
		formatString: #,0.00
		lineageTag: 932be664-eca2-529e-b943-e8cf0800cc0e

	measure '95% VaR (GBP m)' = CALCULATE ( SUM ( fact_risk[value_gbp] ), fact_risk[method] = "hs_equal", fact_risk[measure] = "VaR95", fact_risk[scope] = "total" ) / 1e6
		formatString: #,0.00
		lineageTag: 4074ffaa-9471-5c50-9158-8234ca9c8e12

	measure '97.5% ES (GBP m)' = CALCULATE ( SUM ( fact_risk[value_gbp] ), fact_risk[method] = "hs_equal", fact_risk[measure] = "ES975", fact_risk[scope] = "total" ) / 1e6
		formatString: #,0.00
		lineageTag: d11a093e-930e-54a2-a557-a3142d74af95

	measure 'ES contribution (GBP m)' = CALCULATE ( SUM ( fact_risk[value_gbp] ), fact_risk[measure] = "ES975_contribution", fact_risk[scope] = "desk" ) / 1e6
		formatString: #,0.00
		lineageTag: 6e33c840-b202-51dc-b48f-9393e2bf061b

	column 'date'
		dataType: dateTime
		formatString: d mmm yyyy
		lineageTag: b81395da-187e-5ac1-baca-57ef660f9dcf
		summarizeBy: none
		sourceColumn: date

		annotation SummarizationSetBy = User

	column 'method'
		dataType: string
		lineageTag: 950d4c38-7745-5385-8bc8-53d5d22b9065
		summarizeBy: none
		sourceColumn: method

		annotation SummarizationSetBy = User

	column 'measure'
		dataType: string
		lineageTag: 1bcd67e5-e0cb-5145-b29c-67d8e5f9442b
		summarizeBy: none
		sourceColumn: measure

		annotation SummarizationSetBy = User

	column 'scope'
		dataType: string
		lineageTag: e75e808e-17c8-507c-9d43-0019803c7f95
		summarizeBy: none
		sourceColumn: scope

		annotation SummarizationSetBy = User

	column 'scope_id'
		dataType: string
		lineageTag: e9ca7ba8-fc4b-5ddc-9d8f-419d05b858a7
		summarizeBy: none
		sourceColumn: scope_id

		annotation SummarizationSetBy = User

	column 'value_gbp'
		dataType: double
		lineageTag: da9542b9-c622-59e4-bee8-071cb872987c
		summarizeBy: none
		sourceColumn: value_gbp

		annotation SummarizationSetBy = User

	partition fact_risk = m
		mode: import
		source =
				let
				    Source = Csv.Document(File.Contents(BiFolder & "fact_risk.csv"), [Delimiter = ",", Encoding = 65001, QuoteStyle = QuoteStyle.Csv]),
				    Promoted = Table.PromoteHeaders(Source, [PromoteAllScalars = true]),
				    Blanks = Table.ReplaceValue(Promoted, "", null, Replacer.ReplaceValue, Table.ColumnNames(Promoted)),
				    Typed = Table.TransformColumnTypes(Blanks, {{"date", type date}, {"method", type text}, {"measure", type text}, {"scope", type text}, {"scope_id", type text}, {"value_gbp", type number}}, "en-US")
				in
				    Typed

	annotation PBI_ResultType = Table
